### ISSUE TITLE
Dragging big items

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#108]
Currently to decide which item should go on top when dragging an item from one list to another, we compare the centre positions. However, this often ends up punishing large items and they almost always move below their target. Perhaps we should change the comparison to check the start edge rather than the centre position to see which goes on top. This would therefore not take the size of the item into account and would not punish large items

Your thoughts @jaredcrowe ?

**Comment by alexreardon** [comment]
It would be a fairly trivial change - but it would be worth playing with to see how it feels. No need to tackle this in the short term. I can have a play when i get back

**Comment by jaredcrowe** [comment]
I think it's something we should play around with before we make a call. I can see how it might feel more natural in some circumstances, but it would break this analogy which I think works pretty well in most cases:
![1-i1rjcwq9qwiqu-rxfk4x1g](https://user-images.githubusercontent.com/4995433/30671548-e843dba2-9eaa-11e7-97b8-e933d75d9e63.gif)

Another issue I have with this is that it breaks our 'path of least resistance' philosophy. The moving item would not have to travel as far as it would in our current implementation, but the item it's displacing would actually have to move much further. I've mocked up a comparison of these strategies as they apply to a specific scenario:
![dnd_displacement_strategies](https://user-images.githubusercontent.com/4995433/30672809-fccc9904-9eb1-11e7-9c72-11ddb80bcc18.png)

I'm not ruling this out, but I think that if we go ahead with it we need to take some time to nail down a good analogy (something including a concept of 'mass' maybe) so that we can apply it consistently across every scenario.

**Comment by alexreardon** [comment]
Brilliant take on the situation! The diagrams are awesome as well. This was more an 'idea' I had than anything else. Let's thrash it out later

**Comment by alexreardon** [comment]
I'll close this for now as we do not plan on actioning it at this stage
