### ISSUE TITLE
Improve how we handle errors

### ISSUE THREAD

**Issue by lakesare** [atlassian/react-beautiful-dnd#1108]
## Bug or feature request?

Vague, I'd consider it a bug.

### Expected behavior

React-beautiful-dnd doesn't touch errors that don't relate to it.

### Actual behavior

Instead of one error, I get 5 bulky errors that have nothing do with react-beautiful-dnd.
![image](https://user-images.githubusercontent.com/7578559/52687485-f20a0c00-2f73-11e9-8e10-3acbb3dc45e0.png)

### What version of `React` are you using?
16.7.0.

### What version of `react-beautiful-dnd` are you running?
10.0.3

### What browser are you using?
Chrome.

**Comment by Butch-1337** [comment]
Any updates on this issue?

**Comment by MrBojangles** [comment]
Have recreated the issue where it appears a drag is occuring all the time, at least the error message says so. Can be found [here](https://github.com/MrBojangles/beaut-dnd-err). npm-run-start then click the button

**Comment by cnrudd** [comment]
Seeing same issue on:
React 16.8.4
react-beautiful-dnd: 11.03
Chrome: 74.0.3729.169

**Comment by alexreardon** [comment]
I am a bit busy right now so i cannot pour myself into this one. If somebody wants to take a deeper look at this one just let me know

**Comment by thesuperhomie** [comment]
I'm happy to take this on if nobody else has any objections?

**Comment by alexreardon** [comment]
Go for it!

Here is the logic now:

- any errors on `window`: cancel the current drag
- any `invariant` errors: cancel the drag and swallow the error 👎
- any other errors: cancel the drag and throw the error (which can lead to a double error print as it hits the `window` handler)

Ideally:

- we would capture any internal errors and recover without throwing
- we would not double print other errors

**Comment by thesuperhomie** [comment]
Awesome thanks for the context!

Just a heads up had to edit the rollup config to this:
```js
const commonjsArgs = {
  include: 'node_modules/**',
  // needed for react-is via react-redux
  // https://stackoverflow.com/questions/50080893/rollup-error-isvalidelementtype-is-not-exported-by-node-modules-react-is-inde/50098540
  namedExports: {
    'node_modules/react-redux/node_modules/react-is/index.js': [
      'isValidElementType',
      'isContextConsumer',
    ],
    'node_modules/react-is/index.js': [
      'isValidElementType',
      'isContextConsumer',
    ],
    'node_modules/react-redux/es/components/connectAdvanced.js': [
      'isContextConsumer',
    ],
  },
};
```
for the build to run for me. Not sure if it's happening to anyone else contributing but thought I'd let you know :)

**Comment by alexreardon** [comment]
I think we need to fix this. Right now things suck.

## The plan

### `componentDidCatch`

- If a drag is occurring and any error is received, cancel the drag and when in development mode log that the drag was aborted due to an error
- If the error source was an `rbd` invariant: recover from the error with a `.setState({})`
- If the error source was not `rbd`: throw the error up higher (don't recover)

### Window error event listener

- If a drag is occurring and *any* error occurs (sourced from `rbd` or otherwise), cancel the existing drag. Log a `console` message for development stating that the drag was aborted
- If the error was caused by `rbd` and a drag was not occurring, log the error in development
- If the error was not caused by `rbd` and no drag is occurring, don't do anything

In order to know what errors are caused by our `invariant`'s we will need to (Potentially) move away from `tiny-invariant` so we can throw our own custom error type (something like `RbdInvariant`)

**Comment by alexreardon** [comment]
Given this involves some error recovery behaviour changes, it would be great to get it into our next breaking change version #1317

**Comment by alexreardon** [comment]
Shipping in 12.0!

**Comment by ChessMathNerd** [comment]
Has this been fixed yet? I am getting a similar error, when I rapidly click, drag, drop <Draggable /> components (emulating a bored user's behavior). 
![React-DND-error](https://github.com/atlassian/react-beautiful-dnd/assets/111459529/25e1f63f-9045-46ef-9d4f-200743310b0b)

**Comment by LifeAsDev** [comment]
I get the exact same error as ChessMathNerd when I quickly click and drag
