### ISSUE TITLE
Drag and drop with copy

### ISSUE THREAD

**Issue by Robert-Fish** [atlassian/react-beautiful-dnd#1120]
is it possible to copy the dragged over item e.g dragging item from list one to list two and having dragged item to be duplicated in list one.

**Comment by markdon** [comment]
When you update your state, you'd just make a copy of the data you're 'moving' instead of actually moving it. Pretty sure that would get the right end result but the animations wouldn't be perfect (the source item would get dragged away and pop back after dropping). Unless there's support for this I haven't seen before!

**Comment by EdmundsEcho** [comment]
Brilliant minds think alike.  I believe the issue #216 will provide you with the latest regarding this feature and a way to implement feature.  - E

**Comment by alexreardon** [comment]
I'll close this one as it seems like it has been resolved
