### ISSUE TITLE
How to properly filter item, and skip it index.

### ISSUE THREAD

**Issue by Spaider15** [atlassian/react-beautiful-dnd#1190]
## Bug or feature request?

bug

In my case, i need to save index in array, but filter some items. if i will filter 0 item, then if i will try drag first item after 2, it jumps after two items. if i will return it to first item, it will swap with 0 item, which i filtered.

### Steps to reproduce
Open url, try to drag & drop first item with second. or just start and stop drag it.
https://codesandbox.io/s/4lv3yoq424

### What version of `react-beautiful-dnd` are you running?
10.1.0

### What browser are you using?
Chrome

### Demo
https://codesandbox.io/s/4lv3yoq424
<!--

**Comment by Spaider15** [comment]
Can some one help here?

**Comment by markdon** [comment]
In your render, I don't think you can really just skip rendering an item, since rbd probably expects 
contiguous indexes from 0 to n-1. 

You're skipping the item at index 0 of the current array. Did you really mean to skip whichever item is called 'item-0'?

I don't think there is a really simple way to make a filtered list. You'll kind of need to manage two lists. An unfiltered list and a filtered list that is derived from your unfiltered list.

You render the filtered list as normal with rbd. onDragEnd will receive indexes based on the position of items in the filtered list. You would then need to figure out how to update your unfiltered list based on the source/destination indexes of your filtered list.

**Comment by Spaider15** [comment]
@markdon Thanks for your help. I found how to fix this. just will use display: none for filtered item.

**Comment by pareshetc1** [comment]
@Spaider15 Done great help and worked for me. Thanks
