### ISSUE TITLE
Cannot update droppable registration as no previous registration was found

### ISSUE THREAD

**Issue by Steffi3rd** [atlassian/react-beautiful-dnd#1212]
I have a problem when I delete column using async/await. 

```
Error: Invariant failed: Cannot update droppable registration as no previous registration was found
```
```
Error: Invariant failed: Cannot unregister Droppable with id `12` as as it is not registered
```

1 - I delete column id `3` 

```
await DELETE /column/3
```

2 - Once deleted, I get the new list of columns (without my column `3`)

```
await GET /columns
```

3 - Then I delete a new column id `12`

```
await DELETE /column/12
```

4 - Once deleted, I get the new list of columns (without my column `12`)

```
await GET /columns
```

5 - My column `12` is not here anymore but just second later, there are two errors in a row:
 
```
Error: Invariant failed: Cannot update droppable registration as no previous registration was found
```
```
Error: Invariant failed: Cannot unregister Droppable with id `12` as as it is not registered
```

The id `12` is the one I just deleted in step 3.

I don't understand why, because the list of columns returns by ```await GET /columns``` is updated. 
But React DnD seems to do something with` 12` after I was deleting. 

It seems not synchronized...

Do you have a solution?

**Comment by Steffi3rd** [comment]
https://github.com/atlassian/react-beautiful-dnd/issues/708

**Comment by alexreardon** [comment]
Here is some information which hopefully addresses your issue. I do not have a total grasp of your flow, but I think I can see what is going on. Please correct my understanding if it is off.

So, your flow is:

1. do a drag and drop interaction
2. when the drag ends you fire off some async data updates
3. when the data updates resolve you update the UI

`react-beautiful-dnd` expects your UI to be immediately (optimistically) updated when a drag ends. So that would look like this:

1. do a drag and drop interaction
2. **(done first ↑)** when the data updates resolve you update the UI
3. **(done second ↓)** when the drag ends you fire off some async data updates

### More information

- [onDragEnd guide](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/responders.md#ondragend-required)
- [persisting list order lesson](https://egghead.io/lessons/react-persist-list-reordering-with-react-beautiful-dnd-using-the-ondragend-callback)

Let me know if that is what you needed!
