### ISSUE TITLE
@atlastkit/tree doesn't add placeholder element

### ISSUE THREAD

**Issue by ianschmitz** [atlassian/react-beautiful-dnd#1237]
Sorry if this the wrong forum for the issue. I didn't see any obvious place to post issues on the BitBucket side. This is somewhat related to a previous issue i posted: https://github.com/atlassian/react-beautiful-dnd/issues/1162

## Bug or feature request?

Bug

### Expected behavior
The `@atlaskit/Tree` component renders the `provided.placeholder` in the `Droppable`.

### Actual behavior
No placeholder is rendered. See https://bitbucket.org/atlassian/atlaskit-mk-2/src/f8172af305826842a56ea6f0f31643c38e135656/packages/core/tree/src/components/Tree/Tree.js?at=master&fileviewer=file-view-default#Tree.js-282:310

### Steps to reproduce
See demo below

### What version of `React` are you using?

`16.8.4`

### What version of `react-beautiful-dnd` are you running?

`10.1.0`

### What browser are you using?

Latest Chrome

### Demo

See the console in the following demo. react-beautiful-dnd gets quite upset when there is no placeholder rendered, and because of such the height/width of scroll container changes which also makes it upset :).

https://codesandbox.io/s/x3m88q6rrw

![image](https://user-images.githubusercontent.com/6355370/55832571-b3ec1d00-5aca-11e9-988d-57a64ea2861d.png)

**Comment by alexreardon** [comment]
We are currently tracking @atlaskit/tree issues here: https://ecosystem.atlassian.net/servicedesk/customer/portal/24/create/236

I will be adding this to our upcoming issue templates

**Comment by alexreardon** [comment]
I have also passed this on internally to the team that looks after tree

**Comment by nelsonpecora** [comment]
Hi folks, I'm encountering this as well. I couldn't find anything referencing it in https://ecosystem.atlassian.net/servicedesk/customer/portal/24/create/236. Any good news?

**Comment by spencerkingman-niche** [comment]
Updating my `react-dom` dependency from 16.1.2 to 16.4.2 made the `provided.placeholder` start rendering for me. I am on `react` 16.6.3 and `react-beautiful-dnd` 10.1.1.

**Comment by cusxio** [comment]
Patch it in the meantime

```js
class PatchTree extends Tree {
  render() {
    const { isNestingEnabled } = this.props;
    const renderedItems = this.renderItems();

    return (
      <DragDropContext
        onDragStart={this.onDragStart}
        onDragEnd={this.onDragEnd}
        onDragUpdate={this.onDragUpdate}
      >
        <Droppable
          droppableId="tree"
          isCombineEnabled={isNestingEnabled}
          ignoreContainerClipping
        >
          {dropProvided => {
            const finalProvided = this.patchDroppableProvided(dropProvided);
            return (
              <div
                ref={finalProvided.innerRef}
                style={{ pointerEvents: "auto" }}
                onTouchMove={this.onPointerMove}
                onMouseMove={this.onPointerMove}
                {...finalProvided.droppableProps}
              >
                {renderedItems}
                {dropProvided.placeholder}
              </div>
            );
          }}
        </Droppable>
      </DragDropContext>
    );
  }
}
```

**Comment by nelsonpecora** [comment]
Hi, has there been any update on this?

**Comment by hugw** [comment]
@alexreardon Hello!
Do you happen to have any information regarding this issue?
The url¹ you provided months ago is returning a 404 page which makes it impossible to track it.

1. https://ecosystem.atlassian.net/servicedesk/customer/portal/24/create/236

Thank you in advance!

**Comment by antoniojps** [comment]
Any updates? Seems like a forgotten issue.

**Comment by jagaapple** [comment]
@cusxio Could you use that way?
When I replaced `Tree` Component with `PatchTree` , `Could not find "store" in the context of "Connect(Draggable)"` error has occurred.

https://codesandbox.io/s/atlaskittree-patch-tree-u7rqc

**Comment by satanworker** [comment]
I know that's not an exact place to ask a question about @atlaskit and I apologize in advance. But please if anybody has any info about where to take a look to find info about tree package that would be awesome! 
I'm trying to use a tree with rbd but it seems it's using an outdated form of react beautiful dnd and I can't find anything except 
https://atlaskit.atlassian.com/packages/core/tree. 
rbd is so good I can't believe atlaskit is so frustrating

**Comment by cusxio** [comment]
@jagaapple 

You need to import from `react-beautiful-dnd-next` because that is what the `Tree` package depends [on](https://bitbucket.org/atlassian/atlaskit-mk-2/src/be4cdd0b1f9566847c274d0d05b9549881e0ae4a/packages/core/tree/package.json#lines-27). Unfortunately, that means that if you be stuck using v11 or `rb-dnd`.

https://codesandbox.io/s/atlaskittree-patch-tree-dxmzu

@satanworker , you mean the source code?
https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/packages/core/tree/

**Comment by petermikitsh** [comment]
Hi @alexreardon, got 2 things here:

## 1. Bug discussed in this issue

Per the `@atlaskit/tree` [changelog](https://unpkg.com/browse/@atlaskit/tree@8.1.1/CHANGELOG.md):

> ## 8.1.0
>
>
> ### Minor Changes
> 
> - [`5584033c5e`](https://bitbucket.org/atlassian/atlassian-frontend/commits/5584033c5e) - Fixed missing react beautiful D&D placeholder behavior

It sounds like this issue was addressed, though I'm observing the runtime exception on v8.1.1:

<img width="1292" alt="Screen Shot 2020-09-12 at 2 40 24 PM" src="https://user-images.githubusercontent.com/1571918/93005463-f575c880-f505-11ea-966a-5fa00bdc577a.png">

### 2. Public Mirror

The [atlaskit-mk-2](https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/) repo says non-Atlassian developers should reference the [public mirror](https://bitbucket.org/atlassian/design-system-mirror/src/master/), but I couldn't find `@atlaskit/tree` in the public mirror.

The [FAQ](https://bitbucket.org/atlassian/atlaskit-mk-2/src/be243aff0af7b8dcf6a236c796046a00b45b3854/) (last updated in February 2020): 

> Why have these components all been moved / close sourced?

> In an effort to improve how we manage frontend code across Atlassian, we needed to first co-locate all our front end code in the same place. As a result, we decided to close the Atlaskit repo for a short period of time before re-opening it. You can still view the source (Link coming very soon, this week for certain!)

Could we get the latest source code available in the public mirror? Thanks!

---

Side note: I wish I could contribute to `@atlaskit/tree`, RBD v13 has made great progress since v11, and I noticed `@atlaskit/tree` is on a fork of v11.
