### ISSUE TITLE
Active focus is not preserved on current element when using material-ui dropdowns

### ISSUE THREAD

**Issue by pmjonesg** [atlassian/react-beautiful-dnd#1469]
### Expected behavior
Selecting an option in the dropdown will keep the parent component of the dropdown in the viewport (not jump to a different part of the page).

### Actual behavior
After selecting an option the page will jump back to an element that had the focus (e.g. a search bar in a navigation bar).

### Steps to reproduce

1. Select the search bar at the very top.
2. Scroll down until the search bar is out of view.
3. Select a dropdown and click on an option.

### What version of `React` are you using?

16.9.0
@material-ui/core v4.3.3

### What version of `react-beautiful-dnd` are you running?

11.0.1

### What browser are you using?

Chrome 75.0.3770.142

### Demo
https://codesandbox.io/s/active-focus-5zq3h
- 12.0 -
https://codesandbox.io/s/active-focus-edroy?fontsize=14

**Comment by alexreardon** [comment]
Can you please check on 12.x?

**Comment by pmjonesg** [comment]
Thanks for taking a look, unfortunately I was able to replicate on the latest version (12.0) and added a link to an updated sandbox.

**Comment by alexreardon** [comment]
Does this only effect material ui? Could you please quickly put together an example that just uses `<select>` + `<option>` tags? It would be nice to know if it is issue caused by interacting with material ui or if it a bigger issue with our focus management

**Comment by alexreardon** [comment]
I think the issue is being caused by something else - perhaps material ui. 

I set a breakpoint on the piece of our code that tries to restore focus and it was not being hit in the scenario you described.

<img width="740" alt="Screen Shot 2019-11-12 at 7 51 38 am" src="https://user-images.githubusercontent.com/2182637/68620348-65e83d80-0521-11ea-8cb5-4ea4e2a85109.png">

I checked that the breakpoint was being hit when expected to ensure that the breakpoint was working correctly

**Comment by pmjonesg** [comment]
You're absolutely right, updating `material-ui` to the latest version (`4.8.2`) fixed the issue, thanks again for looking into this.
