### ISSUE TITLE
Items unmount-remount when drag ends

### ISSUE THREAD

**Issue by coffeedoughnuts** [atlassian/react-beautiful-dnd#1650]
### Expected behavior

Items don't unmount-remount

### Actual behavior

Items seem to unmount then immediately remount on drag end

### Steps to reproduce

Demo: https://codesandbox.io/s/vertical-list-gp93p
The item unmount-remounts and that causes the iframe in the item to reload. If you drag Item 0 to Position 1 then the item you dragged remounts. If you drag Item 1 to Position 0 then the item which is now in Position 1 remounts.

### What version of `React` are you using?

16.11.0

### What version of `react-beautiful-dnd` are you running?

12.0.0

### What browser are you using?

Chrome

### Demo

https://codesandbox.io/s/vertical-list-gp93p

**Comment by alexreardon** [comment]
This is expected behaviour for React when reparenting https://github.com/facebook/react/issues/3965

The `useClone` API will move the component to a portal, causing it to reparent

**Comment by alexreardon** [comment]
Ideally, there would be a way to move an element from one parent to another without having the component remount in React

**Comment by Paol-imi** [comment]
I had the same problem in my App, so I tried to develop a library to solve it.

For now I have implemented it with React-dnd, since I believe that in React-beautiful-dnd an external implementation makes little sense. In case, it should be implemented internally.

If anyone wants to take a look at the library, I leave you the Github link.
[**React-reparenting**](https://github.com/Paol-imi/react-reparenting).

You can check the [**example**](https://paol-imi.github.io/react-reparenting/examples) with React-dnd. I took one of its available demos and added 6-7 lines of code. Reparenting works without re-mounting and maintaining the internal state of the component.
