### ISSUE TITLE
Customize the overlap/displacement behavior when Draggables are dragged

### ISSUE THREAD

**Issue by ksimons** [atlassian/react-beautiful-dnd#1670]
### Description

Currently react-beautiful-dnd seems to determine when to move a Draggable out of the way when the Draggable being dragged is over the halfway point of the bounding box. However, if you look at a tool like Trello, the items are displaced based not on the position of the item being dragged but instead based on the mouse pointer position. 

Therefore it would be great react-beautiful-dnd would provide a way to customize this displacement behavior so that we could also use Trello's approach.

**Comment by danieldelcore** [comment]
Hey @ksimons, we recently changed this behaviour in v12 to better support mixed size draggables and droppables, hence why the behaviour is slightly different now. Given the surface area of the logic and crazy amount of edge-cases to consider, i don't think having multiple strategies for this will work for RBD long-term. 

Using the mouse position was something that we considered as well, but we opted against it because it can be awkward for mixed size draggables where grabbing them in the wrong position might require you to drop and pick up again so that you can move the draggable into the correct location. 

Do you have a specific use case that doesn't work (or is awkward) for you now? 😀

**Comment by ksimons** [comment]
Thanks for the explanation @danieldelcore.

The case that we find quite awkward currently is when you have one very large draggable with small draggables above and below it. Trying to drag the large draggable and place it where you want is error prone and very often we see a "jump" right as you release.

**Comment by torarvid** [comment]
Hi, @danieldelcore. I'm trying (and, alas, failing...) to understand what you meant by

> [...] it can be awkward for mixed size draggables where grabbing them in the wrong position might require you to drop and pick up again so that you can move the draggable into the correct location.

Could you possibly explain that differently? The example that @ksimons gives, I believe I get; if you have:

1. vertically stacked draggables
2. each drag handle is at-the-top
3. a container where you stack
    1. a short
    2. then a tall
    3. then a short draggable on top of each other

It could be impossible to then drag the **tall** draggable to the top — because even though the **mouse pointer** can be placed at the top of the container, the mid-point of the **tall** draggable might never make it above the mid-point of the **short** one. And so you end up having to abort, and instead go and drag the short draggable down instead.

**Comment by alexreardon** [comment]
We improved how things feel with vastly different sized items in 12.0. See here: https://dev.to/alexandereardon/overhauling-our-collision-engine-962

> It could be impossible to then drag the tall draggable to the top — because even though the mouse pointer can be placed at the top of the container, the mid-point of the tall draggable might never make it above the mid-point of the short one. And so you end up having to abort, and instead go and drag the short draggable down instead.

**I think that is the 11.x logic:**

- A (small)
- B (large) [dragging]

When the midpoint of B goes over the up over the bottom of A, then A moves down. This might not always be possible

**Current 12.x logic:**

- A (small)
- B (large) [dragging]

When the top of B goes over the midpoint of A, then A moves. This is always possible

**Comment by alexreardon** [comment]
I've closed this for now as I think it is fixed in 12.x. If that is not the case then we can reopen this

**Comment by torarvid** [comment]
Thanks for the update. Small detail: I noticed that after upgrading from v12.0 to v12.2, I saw the change in behaviour that you describe, but anyway — it appears to work nicely in 12.2 👍

**Comment by muhammedmagdi** [comment]
@torarvid How can I customize the displacement size in 12.2? I can't find any docs.

**Comment by torarvid** [comment]
@muhammedmagdi I don't know (but I don't work on this repo, I'm just a casual user who commented on this issue 😉)
