### ISSUE TITLE
Disable keyboard dragging

### ISSUE THREAD

**Issue by inkas** [atlassian/react-beautiful-dnd#1683]
### Description
It would be great if there's an option to disable keyboard dragging. Since keyboard dragging disables mouse dragging while some keys like Ctrl or Shift are pressed, it would be nice to have this feature.

**Comment by conor-kelleher** [comment]
I would also appreciate this feature. I'm using `disableInteractiveElementBlocking` set on my `Draggable` so that I can drag a button covering my whole component. But this is causing trouble in my child components as pressing the space bar is starting a drag event. Would be good to have a separate opt out for keyboard events to help me from having to "monkey patch" the event handlers (see https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/draggable.md#interactive-child-elements-within-a-draggable-)

**Comment by danieldelcore** [comment]
Related: https://github.com/atlassian/react-beautiful-dnd/issues/1601

We now expose the default sensors as public api. You can just pass only the sensors you want and exclude the keyboard one 😄 

Will close this for now, reopen if it's still an issue for you 😄
