### ISSUE TITLE
Can we have multiple rows and columns

### ISSUE THREAD

**Issue by 18355166248** [atlassian/react-beautiful-dnd#1708]
Can we have multiple rows and columns

**Comment by danieldelcore** [comment]
Hey @18355166248, 

Could you please share some more information about your requirements? Are you after some docs on how it can be done? Is there something that we don't support and should? 

Here are some examples from our storybook that might help you:
- [multiple vertical lists](https://react-beautiful-dnd.netlify.app/?path=/story/multiple-vertical-lists--stress-test)
- [multiple horizontal lists](https://react-beautiful-dnd.netlify.app/?path=/story/multiple-horizontal-lists--stress-test)
- [nested vertical lists](https://react-beautiful-dnd.netlify.app/?path=/story/complex-vertical-list--nested-vertical-lists)


Hope that's helpful 😄 

Since this issue is quite old, i'll just close it for now, but if you're still having trouble please feel free to reopen it!
