### ISSUE TITLE
Add BeforeDragStart hook 

### ISSUE THREAD

**Issue by Nizarius** [atlassian/react-beautiful-dnd#174]
## Bug or feature request?
Feature

Hi! This library is awesome. But it looks like we really need BeforeDragStart hook. For example, I want to collapse nested list before i drag it. OnDragStart hook can't help, because react-beautiful-dnd creates mirror before that hook, and cause of that the height of the mirror is the height of the expanded nested list (if it was expended of course).

**Comment by jpsear** [comment]
Could this even actually work though? Even with a `beforeDragStart`, the dragging would have to begin — or nothing would move — which would mean that the snapshot is wrong. The only thing I can think is a `beforeSnapshot` hook, where the initial drag is a complete free-for-all and once the snapshot has been returned, the drop zones become available...

Or perhaps I'm way off the mark and don't get how it's working!

**Comment by dannyberzon** [comment]
👍 for this. I also have to collapse a list when dragging starts - I imagine this is a use case that's quite common,  because with nested lists you want to be able to focus attention on the elements at the level you are dragging. Todoist, for example, will collapse any subtasks within a task when you start to drag it.

I have a list of articles nested within sections, and when dragging sections, I want the articles in the section we are dragging to collapse or hide, and therefore reduce the size of the element being dragged before the dimensions are captured. I can try and hide on dragStart, but the element being dragged has already calculated it's dimensions and you end up with lots of whitespace inside.

I understand that react-beautiful-dnd needs to control positioning and sizing once dragging has started, but is there any way to run code after the user starts to drag the drag handle but before the library collects dimensions?

I've tried adding an onClick to the drag handle but this only fires on mouse up and so is no use. Adding an onDragStart seems to break the dragging. Does anyone have any ideas how the functionality I want can be achieved?

**Comment by alexreardon** [comment]
Consumers might get this for free when we ship #484

**Comment by alexreardon** [comment]
It would involve a double DOM capture when hiding on lift (which is not ideal) - but I think it is a great path forward as it is a streamlined dimension capturing flow

**Comment by alexreardon** [comment]
We *should* be creating an example of how to do this as a part of #484

**Comment by tonnenpinguin** [comment]
This is already implemented according to the docs, right? :)

**Comment by tjramage** [comment]
@alexreardon I'm just reading through the docs... please can you explain the difference between these two points regarding the `onBeforeDragStart` hook?

- ✅ Can apply modifications to existing components to lock their sizes
- ❌ Cannot modify the sizes of any `Draggable` or `Droppable`

Thanks!

**Comment by alexreardon** [comment]
More relevant: #981
