### ISSUE TITLE
innerRef deprecated

### ISSUE THREAD

**Issue by subelta** [atlassian/react-beautiful-dnd#1899]
### Expected behavior
No warning or some new alternative to innerRef, suggested in the docs. 
If you are not planning to switch to something other then innerRef or you think this warning shouldn't be there, please let me know and I'll report this problem to the guys working on code inspections

### Actual behavior
Warning about deprecation of innerRef
<img width="822" alt="Screenshot 2020-07-24 at 16 58 37" src="https://user-images.githubusercontent.com/40162440/88399044-efe5e700-cdce-11ea-97e6-ca5794570412.png">
 And if I try using ref instead of innerRef as the warning suggests, I get an error 
<img width="405" alt="Screenshot 2020-07-24 at 17 01 39" src="https://user-images.githubusercontent.com/40162440/88399432-887c6700-cdcf-11ea-8253-c6ef6dca355d.png">

### Steps to reproduce
do as the docs say and use provided.innerRef

### What version of `React` are you using?
16.13.1

### What version of `react-beautiful-dnd` are you running?
13.0.0 (updated from 11.0.5)

### Demo
your demo features usage of provided.innerRef as well https://codesandbox.io/s/k260nyxq9v

**Comment by danieldelcore** [comment]
Hi @subelta, `innerRef` should still be available and work as of `13.0.0`. Are you using a custom eslint rules or tooling which complains if it sees the string `innerRef`? 

For background, the `innerRef` prop is an old pattern which has been used and since deprecated by popular libraries such as `styled-components` and in your case `reach-router`. Since RBD does not depend on a `innerRef` _prop_ and instead simply returns a ref inside of a variable called `innerRef`, it should be safe and will continue to work. 

Can you have a look and let me know?

**Comment by subelta** [comment]
Hi, @danieldelcore, I can't reproduce this myself, I guess it was a rule or inspection and it was either disabled or fixed, so I'll close this

**Comment by danieldelcore** [comment]
Amazing no worries at all, @subelta 👋
