### ISSUE TITLE
Is it possible to have a DragPreviewImage?

### ISSUE THREAD

**Issue by bendcarmen** [atlassian/react-beautiful-dnd#2018]
Thank you for the great library and forgive my ignorance if there is a simple way to do this that I am unaware of, but I was wondering if there was a way to implement a DragPreviewImage similar to react-dnd with this library?  The use case would be that some items are draggable and some items are not draggable and the non-draggable items would show a red x as the cursor when a user attempts to drag them, otherwise dragging would occur as expected.

i.e:  <Draggable 
             isDragDisabled 
             dragPreviewImage={imageToShowIfNotDraggable} 
              ...otherProps 
         />

thanks for your time.

**Comment by 2stash** [comment]
@bendcarmen 
If I understand your question, this is really easy to implement yourself. Since you know if something has the isDragDisabled prop, you can just dynamically render the cursor into an circle/X with css. Check out this repo and live site for an example and code  snippet from a draggable item.

live site
https://2stash.github.io/react-beautiful-dnd-cursor-example/

repo
https://github.com/2stash/react-beautiful-dnd-cursor-example

Code explanation: Since you put isDragDisabled into a variable, you can use that variable to conditionally render a different cursor. `cursor: "not-allowed` is a nice visual for not being able to drag something and is already included in CSS. 

`import React, { Component } from "react";
import styled from "styled-components";
import { Draggable } from "react-beautiful-dnd";

const Container = styled.div`
  border: 1px solid lightgrey;
  border-radius: 2px;
  padding: 8px;
  margin-bottom: 8px;
  background-color: #fff;
  cursor: ${props => (props.isDragDisabled ? 'not-allowed' : 'grab')}
`;

export default class Task extends Component {
  render() {
    const isDragDisabled = this.props.task.id === 'task-1';
    return (
      <Draggable draggableId={this.props.task.id} index={this.props.index} 
      // isDragDisabled here disables dragging
      isDragDisabled={isDragDisabled}>
        {(provided) => (
          <Container {...provided.draggableProps} {...provided.dragHandleProps} ref={provided.innerRef} 
          // isDragDisabled here added to provided styling
          isDragDisabled={isDragDisabled}>
            {this.props.task.content}
          </Container>
        )}
      </Draggable>
    );
  }
}`

**Comment by bendcarmen** [comment]
Hi Dan,

Thank you for taking the time to provide that elegant solution.  I really appreciate it...and I think that will probably fit our use case.
