### ISSUE TITLE
Working with server

### ISSUE THREAD

**Issue by u-uysal** [atlassian/react-beautiful-dnd#2043]
### Description

I want to see all my issues to stay exactly where they are before refreshing. I know I may use a server. Do I need to send a post request to the server after every move? Is there any example of showing this? @alexreardon

**Comment by mleutenegger** [comment]
Hi,
the way you handle the persisting of data to the backend of your coice purely depends on said backend. This could be anything, from local storage, GraphQL, REST API or many more. Additionally, you might (and in the case of a remote server most definitively will) have to handle a local cache in order to get a fluid behaviour of your application, so putting out specific examples for specific usecases would not make much sense imho.

The tool need to accomplish your goal is the [`onDragEnd` prop on the `<DragDropContext />` component](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/drag-drop-context.md#dragdropcontext-). Every drop event will call the function given to this prop, supplying information about source, target and draggable item as argument. You will have to handle the update to the server yourself and basically need to do this after every *"drop"* the user makes. This is documented in the [basic list example](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/about/examples.md#basic-samples) with [this function](https://codesandbox.io/s/k260nyxq9v?file=/index.js:1245-1512):

```jsx
// ...
onDragEnd(result) {
    // dropped outside the list
    if (!result.destination) {
      return;
    }

    const items = reorder(
      this.state.items,
      result.source.index,
      result.destination.index
    );

    this.setState({
      items
    });
  }
// ...
```
*Note that this example only handles a single list.*

In the example, the list is stored in an array, but the `reorder()` function could be anything you want it to be. Personally, I like to use GraphQL and the [Apollo GraphQL](https://www.apollographql.com/docs/react/) library for GraphQL, but as I have stated, anything is possible.

**Comment by u-uysal** [comment]
Thank you so much for answering my question @mleutenegger.  Much appreciated.
