### ISSUE TITLE
Duplication when moving draggables too fast

### ISSUE THREAD

**Issue by incogiscool** [atlassian/react-beautiful-dnd#2475]
## Check your console
Console when error starts to occur: 
![image](https://user-images.githubusercontent.com/94598096/213987562-b9698ab4-d37e-4295-a0e1-3b7c94707a04.png)

### Expected behavior
To update seamlessly no matter speed
### Actual behavior
If moving draggables with speed, it crashes

### Steps to reproduce
Set up regular draggable/droppable tabs and columns (similar to the tutorial) and move the droppables between each column fast.

### What version of `React` are you using?
Latest version of NextJs - v13

### What version of `react-beautiful-dnd` are you running?
    "react-beautiful-dnd": "^13.1.1",

### What browser are you using?
Brave

### Demo
https://www.loom.com/share/757abd5ef3464681a1c625b2ef950e51

When a maintainer asks a question about an issue and it is not responded to within a reasonable time frame then the issue will be closed. We don't want this to happen - but we also do not want to accumulate stale issues

Here is the moving code -- Followed tutorial

```javascript
  const onDragEndHandler = ({
    destination,
    source,
    draggableId,
  }: DropResult) => {
    console.log("drag end");

    // console.log({ destination, source, draggableId });
    if (!destination) {
      return console.log("no destination");
    }

    if (
      destination.droppableId === source.droppableId &&
      destination.index === source.index
    ) {
      return console.log("Dropped in same place");
    }

    if (list == undefined) return console.log("list undefined");

    const start = list.columns[source.droppableId];
    const finish = list.columns[destination.droppableId];

    if (start === finish) {
      const newItems = Array.from(start.items);
      newItems.splice(source.index, 1);
      newItems.splice(destination.index, 0, draggableId);

      const newColumn = {
        ...start,
        items: newItems,
      };

      const newState = {
        ...list,
        columns: {
          ...list.columns,
          [newColumn.id]: newColumn,
        },
      };

      if (listIndex === undefined)
        return console.log("list index undefined, ", listIndex);

      const arrOfLists = userDoc.dndLists;
      arrOfLists[listIndex] = newState;

      setList(newState);
      setUserDoc({ ...userDoc, dndLists: arrOfLists });
      // setUserDoc({ ...doc, dndLists[]})

      return;
    }

    // Moving from one list to another
    const startItems = Array.from(start.items);
    startItems.splice(source.index, 1);
    const newStart = {
      ...start,
      items: startItems,
    };

    const finishItems = Array.from(finish.items);
    finishItems.splice(destination.index, 0, draggableId);
    const newFinish = {
      ...finish,
      items: finishItems,
    };

    const newState = {
      ...list,
      columns: {
        ...list.columns,
        [newStart.id]: newStart,
        [newFinish.id]: newFinish,
      },
    };

    if (listIndex === undefined)
      return console.log("list index undefined, ", listIndex);

    const arrOfLists = userDoc.dndLists;
    arrOfLists[listIndex] = newState;

    setList(newState);
    setUserDoc({ ...userDoc, dndLists: arrOfLists });

    // console.log({ userDoc, list });

    // console.log(newState);
  };
```

**Comment by loeffelr** [comment]
have the same problem, can confirm this bug!

**Comment by trey-wallis** [comment]
I got the same problem. I notice that it happens in the official examples as well. See: https://codesandbox.io/s/react-beautiful-dnd-board-base-0dv9b

**Comment by darren-finch** [comment]
After playing around with this problem for a while, I have a hunch at what may be causing the problem and I also have discovered what seems to be a workaround, although it is definitely not optimal.

Steps to reproduce:

1. Go to [this sandbox](https://codesandbox.io/s/exciting-knuth-wiqt1t).
2. Quickly drag and drop the first card in the first column into the second column.
3. Before that drop has fully finished, pick up the second card in the first column. This will generate a warning saying `You are attempting to add or remove a Draggable while a drag is occurring. This is only supported for virtual lists.`
4. Finally, drop the second card into the second column. You will get an error that says `TypeError: quote is undefined`

The issue is that when you remove the second card from the first column, the first drop has not had a chance to finish updating the state of the board yet (because `setState` is asynchronous). Therefore, when `react-beautiful-dnd` generates the result object for `onDragEnd` for the second drag, which it seems to do when the drag starts, it detects that the index of the second card is what it was before the first drag started (1 to be exact). But once `setState` for the first drag completes, that index is no longer correct because the first card was removed and placed into the second column. This results in either:

1. The card that is after the card being dragged in the source column gets dropped into the destination column, and the card being dragged gets put back into the source column (which is definitely incorrect behavior).
2. If there is no card after the card being dragged in the source column, then an error will occur that says the card from the source column is undefined. This is what occurs in the sandbox example.

A temporary workaround to this issue is to run the `setState` function synchronously using `flushSync`. To see this in action, go to `/src/dnd/board/Board.js` in the sandbox and uncomment lines 83 and 85. I have not had any errors occur with this approach, however, it is definitely suboptimal to run `setState` synchronously, so further investigation of this issue is needed.
