### ISSUE TITLE
Add something like isDragOccurring to Droppable snapshot

### ISSUE THREAD

**Issue by tnrich** [atlassian/react-beautiful-dnd#256]
Hey there,

I would like to know in the <Droppable/> list whether or not a drag is occurring. I couldn't figure out how to do that currently and a seemingly easy way to get it would be if the "snapshot" had something like `snapshot.isDragOccurring` on it.

It seems like if another prop were passed here: https://github.com/atlassian/react-beautiful-dnd/blob/0fb4dc75ea9b625f64cac48602635ac2822f26ec/src/view/droppable/connected-droppable.js#L73
to the <Droppable/> component we could get that. 

Or maybe there is just a better way to know within a <Droppable/> whether or not a drag is occurring?

Thanks for the help in advance!

**Comment by alexreardon** [comment]
Hi @tnrich,

It is possible to get the information you need today with the `Hooks > onDragStart` callback in the `DragDropContext`. You can use this callback to set some state that filters down to your components so they can know when a drag is occurring.

We have not added them to the snapshots because this information is already available through the hooks. Also, adding it would cause a re-render of components on drag start / end to pass this value - which has significant performance implications at scale. 

Cheers
