### ISSUE TITLE
Breaking changes from 3.0 to 4.0

### ISSUE THREAD

**Issue by ndrabins** [atlassian/react-beautiful-dnd#262]
Hi, I noticed that trying to upgrade from 3.0 to 4.0 breaks at least a few things. 

1. The way draggable styles are applied. 

In 3.0 the examples and docs use ```provided.draggableStyle``` however in 4.0 the library uses ```provided.draggableProps.style```. If you don't change to this then dragging any object won't show anything to the user. 

2. Another change I found was the way indexes are calculated. Previously source and destination index would be 0 to array.length. Now the source and destination index are relative. For example, if I pick object at index 2 and move it 1 backward, its destination will now be -1 instead of 1. This changes the way a program has to interpret the user moving items. 

Would it be possible to make some kind of migration guide or list of breaking changes? 

Thank you so much for all the work you have put into this library, it is great.

**Comment by alexreardon** [comment]
Hi @ndrabins, yes there were breaking changes going from 3.0.0 to 4.0.0. You can read about all the changes [in the release notes](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v4.0.0). Hopefully that is a sufficient migration guide. If not, please let me know and I can add some more detail to it. Do you think it is is worth calling out this guide at the top of the `readme`?

According to [Semantic Versioning 2.0](https://semver.org/) updating the major version (the number in the first position) is the correct way of indicating a breaking change. The release does also call out which changes are breaking.

> Given a version number MAJOR.MINOR.PATCH, increment the:
>
>**MAJOR version when you make incompatible API changes,**
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.

I suspect your second issue is caused by not adding an `index` of type `number` your `Draggable`s which is now required. This is also detailed [in the release notes](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v4.0.0). 

> Thank you so much for all the work you have put into this library, it is great.

You're most welcome 👍

**Comment by ndrabins** [comment]
Oh wow, yea I just completely missed the release notes! These are great. Thanks for putting these together!

I think it may be helpful to have some mention of moving from 3.0 to 4.0 on the readme. For me atleast, I couldn't find anything mentioning breaking changes on the readme and it never occurred to me to look at the release notes.

**Comment by lukebatchelor** [comment]
#263 referenced above adds a link already. 👌
