### ISSUE TITLE
Droppable-aware Draggables

### ISSUE THREAD

**Issue by lukebarnard1** [atlassian/react-beautiful-dnd#287]
## Bug or feature request?

Feature

## Description

It would be super nice to have `Draggable`s that are aware of the ID of the thing that they are being dragged over as opposed to just `isDraggingOver`.

This would allow the component to render according to the `Droppable` over which it is being dragged.

(We need this over at Riot.im for a fun feature that's in development)

**Comment by alexreardon** [comment]
That sounds interesting! This information is currently available through the `DragDropContext > onDragStart` hook. You can capture this information there and push it down to your `Droppable` components.

**Comment by alexreardon** [comment]
For now i'll close this as what you are attempting to do is possible. But we could look at providing this information in the future directly to droppables

**Comment by lukebarnard1** [comment]
>For now i'll close this as what you are attempting to do is possible.

I'm not sure if I was clear enough.

If you drag something over a droppable that wasn't the source droppable, onDragStart is not fired a second time.

**Comment by alexreardon** [comment]
You can capture the dragging item using the onDragStart hook. You can then pass that information around your app - including your Droppables. You could add the draggableId into your state / props / store

**Comment by lukebarnard1** [comment]
But the state of the dragging item does not include the ID of the droppable that it is currently being dragged over. Droppables don't have any event fired when a draggable is dragged over them, so there is no way of doing this.

If we capture the dragging item using onDragStart, and pass that to all droppables, this still does not allow us to distinguish between a draggable that is being dragged over droppable A and one being dragged over droppable B.

We only get this information when a drop occurs, I'm suggesting that it is available between the drag starting and the drop.

**Comment by alexreardon** [comment]
> Droppables don't have any event fired when a draggable is dragged over them, so there is no way of doing this.

We currently supply a `DroppableSnapshot > isDraggingOver` prop to let `Droppable`s know when they are being dragged over: [here is the docs](https://github.com/atlassian/react-beautiful-dnd#2-snapshot-droppablestatesnapshot)

In combination with the onDragStart which gives you the draggableId you should have everything you need 👍

**Comment by lukebarnard1** [comment]
Okay, so let's suppose the droppable knows the `draggableId` and the `isDraggingOver` flag is set. 

The droppable can now pass this information to its children but not to the draggable, which in this scenario is being dragged from another droppable (unless we decide to make side-effects during a render and fire a dispatch to set some state in the draggable). That is, unless the draggable is in fact a child in the new droppable before it gets dropped? which I don't think is true.

**Comment by alexreardon** [comment]
Hi @lukebarnard1, my appologies - I misunderstood your original request. I thought you wanted a `Droppable` to be able to tell what `Draggable` is being dragged over it. You are interested in knowing from a `Draggable` what `Droppable` it is currently over.

For now as you said the way to do it is to perform some actions in response to `Droppable > isDraggingOver` but it would take some heavy lifting. You would need to publish the `Droppable > isDraggingOver` change into some place that your dragging item could read it in order to know that is is dragging over that.

I think your originally request is reasonable - some more information in the `DraggableSnapshot` would make this really easy for you.

I have created a new issue to track this request, and some other pieces of work that I think are related.

Thanks @lukebarnard1

**Comment by lukebarnard1** [comment]
Hi @alexreardon, no worries, sorry for confusion and thanks for tracking 🙂👍
