### ISSUE TITLE
Remove requirement that a Draggable needs to reside a Droppable

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#29]
This will allow some interesting drag and drop patterns. I want to investigate some use cases - but i'll keep this here as an 'idea' for now

**Comment by jjenzz** [comment]
@alexreardon I have a feeling I might need this. 

I have a use-case where I want to move `<Draggable />`s into `<Droppable />`s without shifting the `<Droppable />`s children out the way because this suggests ordering. I just want to be able to specify which "buckets" things belong to (no ordering).

Is there currently a way to do this? Apologies if I've explained myself terribly!

**Comment by alexreardon** [comment]
Related #188. Draggables need to currently be inside Droppables. The Droppable itself can reject drops (isDropDisabled) and so just be a container.

**Comment by alexreardon** [comment]
@jjenzz I will look into your question

**Comment by alexreardon** [comment]
All you would need is to disable the drop animation (which is currently not possible). Lots of people are asking for that! I am in two minds about it right now. I'll create another issue to discuss

**Comment by alexreardon** [comment]
For now you can stop the movement of anything in a seperate list by adding a `transform: none` with high enough css specificity. That would disable the movement of items
