### ISSUE TITLE
Draggable is animated weird when Dropped

### ISSUE THREAD

**Issue by 12tp12** [atlassian/react-beautiful-dnd#313]
Hey, 

First I have to mention that this library is awesome!
My issue is the following:
When I drag a Draggable to a new list (**Just a new list!**) the dragabble element is jumping and then comes to the right place- sort of a delay.
I have seen similar issues that were close such as:

- Incorrect drop animation on empty list #179 

I have attached the demo.

Thanks!

![jumping-draggable](https://user-images.githubusercontent.com/12761398/35983554-e93a767e-0cfa-11e8-8052-a61a46a8159e.gif)

**Comment by Tmw** [comment]
I'm hitting the same issue. First I thought I missed something, but I saw exactly the same behavior once I rewrote one of the examples (vertical list) a bit to render two lists side by side.

Example: https://codesandbox.io/s/llp145rroq

**Comment by 12tp12** [comment]
Thanks ill try :)

**Comment by alexreardon** [comment]
The issue is caused by the `Droppable` containing extra elements. Right now a `Droppable` can *only* contain draggables and not the column header. To fix the issue move your column header above the `Droppable`. 

This is kind of lame as it means you won't be able to drop items onto the header itself - but it is how the library works at this stage!
