### ISSUE TITLE
Have a clear polyfill story

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#320]
from #319 

We are currently using array.prototype.find in a few places which is not awesome for ie11. Either we need to be clear about what polyfills are required, or remove any usages of prototype methods that require > ie 11.

**Comment by lukebatchelor** [comment]
Personally I'd be in favour of calling it out in the docs and having a warning presented in the console. 

```js
if (!Array.prototype.find) {
  console.warn('Array.prototype.find support not found, please include a polyfill if you would like to support this browser's);
}
```

Could strip the whole thing out in production builds if you wanted to too.

Ie11 will never support find, so doing anything else would be locking yourself in to including this polyfill everywhere, forever. 

If you wanted to be even more explicit, maybe you could use https://github.com/paulmillr/Array.prototype.find instead of Babel polyfill? I think that would be worse in general though, more chance you could miss it, more chance you'd need more polyfills later.

**Comment by alexreardon** [comment]
Thanks @lukebatchelor

**Comment by alexreardon** [comment]
I think it might be best just to avoid .find alltogether and use a .filter[0]

**Comment by alex6633** [comment]
Hi @alexreardon ,
Good day !!! :)

It was working for me in IE11 perfectly with the help of babel-polyfill along with the below versions
 --> "react-beautiful-dnd": "^5.0.0",
--> "babel-polyfill": "^6.26.0",
But now It again gives me the same error in IE11 "Object doesn't support property or method 'find'"
these are my current versions of babel-polyfill and react-beautiful-dnd
-->  "babel-polyfill": "^6.26.0",
-->  "react-beautiful-dnd": "^7.1.2",

[#319](https://github.com/atlassian/react-beautiful-dnd/issues/319)


Do I need to make any changes in the versions of react-beautiful-dnd or polyfill what I am using ?
Could you please help me on this.

**Comment by alexreardon** [comment]
This will be done as a part of #838
