### ISSUE TITLE
Disable Move animaitons?

### ISSUE THREAD

**Issue by mmairs9** [atlassian/react-beautiful-dnd#387]
Is it possible to disable the droppable move animation for items and instead have the drag item swap position by dragging on top of droppable item?

**Comment by alexreardon** [comment]
At this stage no. It goes against the core [characteristic of physicality](https://github.com/atlassian/react-beautiful-dnd#driving-philosophy-physicality) that we are going for

**Comment by sambokai** [comment]
This seems like an arbitrary limitation. Shouldn't the user of the library make design decisions like this?

**Comment by TimNZ** [comment]
@sambokai how/where did you hack a fix to this?
I want to disable the transform/animations on the other items moved after a drop

**Comment by pastukhVitalii** [comment]
> @sambokai how/where did you hack a fix to this?
> I want to disable the transform/animations on the other items moved after a drop

@TimNZ Did you have found a solution to this problem?

**Comment by TimNZ** [comment]
@pastukhVitalii
https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/drop-animation.md#skipping-the-drop-animation

**Comment by trattles** [comment]
@TimNZ I believe the poster might be wanting to stop the "sort" animation that happens by default - rather than simply the drop animation that occurs at the end.

I agree that turning off sort would be an excellent addition to the library. The library is great - but unnecessarily clunky when you want to add a dropzone that doesn't sort and instead has like an overlay or some such (to avoid the auto sorting as mentioned).

The only way I've found to do this involves adding an extra Droppable. You make the Droppable that contains actual draggables set to "isDropDisabled=true" and then render another Droppable on top that allows dropping, but places the dropped item into the underlying droppable.
