### ISSUE TITLE
Support snap scroll ?

### ISSUE THREAD

**Issue by crapthings** [atlassian/react-beautiful-dnd#408]
something like this?

https://alvarotrigo.com/fullPage/#page2

and this example work on ios 11.2.6 only css

the second one

https://webkit.org/demos/scroll-snap/

**Comment by crapthings** [comment]
after i change css to not use flexbox then it starts to work

but when i drag my deck, it looks messy

```
.board
  // display flex
  // width fit-content
  // background-color red
  white-space nowrap
  overflow-x auto

.deck-container
  // display flex
  // flex-direction column
  // width 100vw
  display inline-block
  width 80vw
```

```

.scroller {

  -webkit-overflow-scrolling: touch;

  -webkit-scroll-snap-type: mandatory;

      -ms-scroll-snap-type: mandatory;

          scroll-snap-type: mandatory;

  /* older spec implementation */
  -webkit-scroll-snap-destination: 0% 100%;
      -ms-scroll-snap-destination: 0% 100%;
          scroll-snap-destination: 0% 100%;
  -webkit-scroll-snap-points-x: repeat(100%);
      -ms-scroll-snap-points-x: repeat(100%);
          scroll-snap-points-x: repeat(100%);
}

.page {
  scroll-snap-align: start;
}
```

**Comment by crapthings** [comment]
ah its really bad, css snap will break autoscrolling

**Comment by alexreardon** [comment]
I did not even know this was a thing :|

It looks like a fairly new browser feature with quite poor support

> This is an experimental technology
> Check the Browser compatibility table carefully before using this in production.
> - [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type)

While this might be useful to add at some point I think there are many other additions we could look into before pursuing this.

**Comment by alexreardon** [comment]
I will close this for now as it is not well supported by browsers. We can look into supporting this feature when the browser support is better

**Comment by crapthings** [comment]
https://webdesign.tutsplus.com/tutorials/how-to-scroll-snap-using-css--cms-30333

https://www.chromestatus.com/feature/5721832506261504

extra info chrome update

**Comment by Sebs030** [comment]
Hi, were you able to implement scroll snap? I am trying so, but I don‘t get it working, it would significantly improve the user experience on mobile devices where you usually only show one Droppable Column on a screen and have users scroll horizontally to switch between the columns

**Comment by Sebs030** [comment]
Ok, i got i working like so for vertical scrolling:
`// all other imports....`
`import styled from 'styled-components';`


`const ScrollSnapContainer = styled.div
scroll-snap-type: x mandatory;
overflow-x: auto;
overflow-y: hidden;
`

`const ScrollSnapChild = styled.div
scroll-snap-align: center;
`
and then inside the React Class:
`render() {
        return (
            <div className='container-fluid'>
                <ScrollSnapContainer className="row flex-row flex-nowrap">
                    <DragDropContext onDragEnd={this.onDragEnd}>
                        <ScrollSnapChild className="col">
                            <Droppable droppableId="droppable">`

So this is still a very experimental feature and only works well in Chrome. I doesn´t work at all on iOS even in a Chrome browser and doesn´t work in Safari on a Mac (but in Chrome). Other browsers I have not tested so far. It works nicely on Android devices but it would be needed to add a Zoom-Out functionality on DragStart because othewise you can´t move the cards;) I am leaving this here in case others have the same idea/problems with this topic

**Comment by jescowuester** [comment]
We're at [94% on mobile browsers now](https://caniuse.com/css-snappoints), any chance this issue will be reopened? Scroll snapping itself is working fine between containers but currently, it doesn't scroll when you drag a card to the edge of the container
