### ISSUE TITLE
how can i get  the source code of multiple horizontal lists stress test of react-beautiful-dnd?

### ISSUE THREAD

**Issue by ghaithbriki89** [atlassian/react-beautiful-dnd#435]
Hello there i'm a searching for [horizontal-multiple](https://react-beautiful-dnd.netlify.com/?selectedKind=multiple%20horizontal%20lists&selectedStory=stress%20test&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) code source so i can use it in my project thanks in advance !!

**Comment by ghaithbriki89** [comment]
@alexreardon can you help me?

**Comment by lukebatchelor** [comment]
Hiya, you'll have to dig a little as its spread across a few files, but it starts here if that helps 

https://github.com/atlassian/react-beautiful-dnd/blob/master/stories/5-multiple-vertical-lists-story.js

**Comment by ghaithbriki89** [comment]
@lukebatchelor no there is pleinty of files and import i want a simple one like in jsfiddle r i dont know

**Comment by ghaithbriki89** [comment]
![image](https://user-images.githubusercontent.com/36076752/38614218-9a640a66-3d8c-11e8-9acf-9dbf24418e4d.png) this is my work is the same as 
![image](https://user-images.githubusercontent.com/36076752/38614231-a47f794a-3d8c-11e8-941b-59564e05d102.png)

**Comment by Frozenlock** [comment]
@ghaithbriki89 What you are doing is incredibly rude.

You ask how to do something in a github issue. You're not asking for a new feature, or reporting a bug, but simply asking how to use the tool. This alone wouldn't be too bad, but you're asking for something that is already well within your reach if you simply read the (very) complete readme.

**Whithin the same day** you ping the project maintainer because no one took time out of their day to answer your question.

Then, when someone points out where you can start your search for the source code, you don't even thank them for their time, you simply say something along the lines of "No, I want something I can simply copy paste."

You're burning all the goodwill people might have given you on harder problems.

My suggestion is to follow the readme and try to build your stuff with it.
It's probably easier than simply copying bits from the example's source code and there's a better chance you'll understand the different mechanics.
You can even start with a vertical droppable and switch later to the horizontal one if you're not so sure about how to things.
