### ISSUE TITLE
Is it possible to style a lane when a card is dragging over it, if it is not droppable?

### ISSUE THREAD

**Issue by aditigoel23** [atlassian/react-beautiful-dnd#480]
## Bug or feature request?
Feature request

When an item is dragged, I want to style the lanes to show which one is a valid drop zone and which one isnt. In my use case you cant drop an item in the same lane you picked it from. So I am setting the isDropDisabled to true for the lane when a card starts to drag from that lane.

While I can check for isDraggingOver along with isDropDisabled for styling valid drop lanes, the isDraggingOver is not set when a lane has isDropDisabled to true. 

Any suggestions?
Thanks!

**Comment by alexreardon** [comment]
Super interesting request @aditigoel23. 

For now you *could* achieve this by adding your own `mouseover` and `mouseleave` event handlers to a droppable. For a disabled droppable you could style it how you want. This will work with keyboard dragging too as it is not possible to move over a disabled droppable

### Assorted thoughts for future me:

Right now it is not possible as we exclude disabled droppables from most calculations. However, I think that information could be useful. 

What would be involved to get this working:

- update dragging over algorithms to not exclude disabled items 
- update the DroppableStateSnapshot
- do not displace anything

This gets complicated because it changes how our onDragEnd and onDragUpdate functions work as they currently only publish valid drop positions.

While this could be useful it will take a fair amount of thinking to get right. I will put it on the back burner for now and have more of a think about it.

### Current thinking

The mouseenter and mouseleave handlers seem like a good solution for now for those who want this behaviour and involves no big changes to anything

I'll close this for now as I think this is a sufficient solution. It would be worth adding some docs about this thought

**Comment by shawninder** [comment]
If `onDragStart` you add a "dragging" class to your <body>, then the rest might be doable via css:
`body.dragging .lane:hover { background: grey; }`
Not tested, just a thought.

**Comment by alexreardon** [comment]
Correct. When a list is disabled it is ignored from the system and will not have any snapshot values updated. CSS could be the way to go

**Comment by NuclleaR** [comment]
> If `onDragStart` you add a "dragging" class to your `<body>`, then the rest might be doable via css:
> `body.dragging .lane:hover { background: grey; }`
> Not tested, just a thought.

Seems like this solution doesn't work in safari
`body.dragging .lane:hover { background: grey; }` works while just hover with mouse
but id drugging seems like `.lane:hover` didn't trigger
