### ISSUE TITLE
Severe performance issues with list of 1000+ items

### ISSUE THREAD

**Issue by guyasino** [atlassian/react-beautiful-dnd#667]
## Bug or feature request?

Bug

### Expected behavior
Have good performance with any time of data set

### Actual behavior
Severe performance issues with list of 1000+ items
Lagging in both dragging and dropping.

### Steps to reproduce
Can be reproduced in the given example in the readme:
https://codesandbox.io/s/pj5yk7kzrj
Increase the number if items and see
The issue gets move severed as the items are getting more complexed.
Can provide our code samples also if needed

### What version of `React` are you using?
16.4.1

### What version of `react-beautiful-dnd` are you running?
8.0.3

### What browser are you using?
Chrome

**Comment by alexreardon** [comment]
I would not advise going about 500 at this stage. This is due to drag and drop performance. But also react takes a long time to render big lists and to reorder them. We will hopefully soon start working on adding virtualisation support #68 which should yield great performance regardless of list size
