### ISSUE TITLE
Placeholder when dragging between droppables

### ISSUE THREAD

**Issue by dmarkow** [atlassian/react-beautiful-dnd#751]
## Bug or feature request?

Feature Request, and maybe a bug too

Using the [multiple vertical list stress test example](https://react-beautiful-dnd.netlify.com/?selectedKind=board&selectedStory=simple&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel):

![kapture 2018-08-24 at 18 09 38](https://user-images.githubusercontent.com/8009/44611795-080af100-a7c9-11e8-9d03-c142a921421c.gif)

- When I grab an item in the zeta droppable and move it up and down, everything flows smoothly and there is no placeholder for the original position
- If I then drag that item down into the eta droppable, a blank placeholder opens up in the last column where the item was originally. This probably makes sense, because without it the zeta droppable would suddenly shorten and the eta droppable would shift up.
- However, after dropping the item into eta and the animation completing, the blank placeholder in zeta disappears abruptly. So after just dropping an item, the mouse is now hovering over a different item.

It seems that the placeholder disappearing in this manner might violate the "no instant movement" philosophy?

My personal issue I'm running into is that I want to drag between multiple vertically stacked lists (similar to the zeta/eta example portion of the stress test page). Everything animates nicely while hovering and there are no issues dragging within the same Droppable, but when I drop the item into a different Droppable, it animates and then suddenly my entire list jumps a little when the placeholder in the source Droppable disappears.

I might be able to work around this by making my set of sections one big Droppable instead, but it would be nice to have an option to hide the source placeholder when you drag outside of the Droppable.

**Comment by alexreardon** [comment]
> It seems that the placeholder disappearing in this manner might violate the "no instant movement" philosophy?

Yep! I am keen to improve this asap

There are a few placeholder issues floating around and this one is probably closer to #77. I hope to work on this soon!!

**Comment by JReinhold** [comment]
I'm experiencing this problem as well, but in a more severe manner. My `Draggables` and `Droppables` are pretty big, which means that we often have to scroll the whole page when dragging vertically between lists that are stacked vertically.

This means that when a `Draggable` is dropped, the instant movement becomes instant window scroll, which is a really confusing user experience, because it almost feels like the `Draggables` are "replacing" each other somehow.

You can experience this by:
1. Go to the [Vertical Stress Test](https://react-beautiful-dnd.netlify.com/?selectedKind=multiple%20vertical%20lists&selectedStory=stress%20test&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
2. Go full screen
3. Zoom in on the "delta" and "epsilon" lists, so they take up the whole window
4. Drag between the lists

my brain tells me, that it is actually only the headline of "epsilon" that moves when I drop, and not the `Draggable` at all.
