### ISSUE TITLE
Question : can we fetch more informations of Drop target than "result.destination.DroppableId" on DragEnd ?

### ISSUE THREAD

**Issue by Aarbel** [atlassian/react-beautiful-dnd#784]
Hi teams,

Is there a way to add more informations about a Droppable Component inside the result of a Drag End ?

For example, in addition to `destination.droppableId`, i would like to add a `destination.myCustomDataIWantToUse`
![image](https://user-images.githubusercontent.com/25119847/45113541-f4597600-b14a-11e8-936c-c6ea620adc89.png)

Maybe putting other props to the Droppable Component ? ...

Thanks a lot for your help !

**Comment by Aarbel** [comment]
Best solution i've found for the moment is to use a complex id for `DroppableId`, and then parse it with sexy Regex..

**Comment by alexreardon** [comment]
Here is some more thinking on the subject: https://github.com/atlassian/react-beautiful-dnd/issues/498

**Comment by Aarbel** [comment]
thanks @alexreardon

**Comment by tslocke** [comment]
@Aarbel the following hack might help you

https://github.com/atlassian/react-beautiful-dnd/issues/498#issuecomment-420608986

**Comment by Aarbel** [comment]
thanks a lot @tslocke !

I used JSON.stringy and JSON.parse to pass many variables in the id. Works very well

**Comment by NunoCardoso** [comment]
I have been using this plugin, and it rocks. This is the last feature I need from it. 

In my case, I have a web application where I have a top DragDropContext, and I can have different Draggables and Droppables going back and forth. 

I use a "gatekeeping" approach where I just listen to onDragEnd, check source and destination, and then decide what to do. 

If I accept the drop, then I want to dispatch the dragged element through Redux. It would greatl help if I that dispatch could be self-sufficient, I mean, I have the full element inside onDragEnd event. 

JSON encoding into id is not a good idea for me, as some of the droppables are actually PDFs (for some reasons, I need the base64 AND the data version of it)

Also, in a less elegant way, I can have the droppables to "send" themselves through Redux through a "onBeforeDragStart" callback, so that onDragEnd can later load them through state, thus not needing to add them on the onDragEnd event.
