### ISSUE TITLE
add babel-runtime as peer dep?

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#845]
We are currently spitting these imports in our `esm` build:

```js
import { getRect, withScroll, createBox, offset, getBox, calculateBox } from 'css-box-model';
import _extends from '@babel/runtime-corejs2/helpers/esm/extends';
import invariant from 'tiny-invariant';
import _Object$keys from '@babel/runtime-corejs2/core-js/object/keys';
import _Object$values from '@babel/runtime-corejs2/core-js/object/values';
import memoizeOne from 'memoize-one';
import { applyMiddleware, createStore, compose, bindActionCreators } from 'redux';
import _Object$assign from '@babel/runtime-corejs2/core-js/object/assign';
import rafSchd from 'raf-schd';
import _inheritsLoose from '@babel/runtime-corejs2/helpers/esm/inheritsLoose';
import React, { PureComponent, Component, Fragment } from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import _Number$isInteger from '@babel/runtime-corejs2/core-js/number/is-integer';
```

A fair few imports from `@babel/runtime-corejs2`. 

Should we call this out explicitly as a peer dependency? Something else?

Thoughts @TrySound @lukebatchelor ?

**Comment by lukebatchelor** [comment]
Hmmm. I'd not seen corejs2 before. But they should be dependencies if anything is say. I don't see an advantage to peerDeps. 

Might want to just double check that it's from babel 7 though.

**Comment by alexreardon** [comment]
Modular Babel runtime

**Comment by TrySound** [comment]
Don't do that please. This will break every user when babel will be increase major version. Or even break now if users still use alpha,beta,rc versions or consume packages with such versions.

What the problem are you trying to solve? Everything works fine.

**Comment by alexreardon** [comment]
What if a consumer is not using Babel? The the esm build would not work. Right now it is a soft dependency. I think it could be worth explicitly calling it out as a dep. we could have a fairly loose range

**Comment by TrySound** [comment]
@alexreardon It doesn't matter that consumer is not using babel. This is a direct dependency similar to tiny-invariant or redux. Think of it like you wrote it by hands. User consumes babel runtime like any other transitive dependency.

Esm doesn't work only with rollup if consumer doesn't use rollup-plugin-commonjs because core-js stuff is cjs.

**Comment by TrySound** [comment]
The point is that babel runtime is reused if possible. This possibility gives npm/yarn partially flatten node_modules. So if two packages has this version it will be reused. If another one package has different version it will be kept inside its nested node_modules.

```
node_modules
  package-1
  package-2
  @babel/runtime // dependency of package-1 and package-2
  package-3
    node_modules
      @babel/runtime // different version is nested to not conflict with the root one
```

And this duplication is okay for safety. Even more nested runtime with the root version will be deduplicated only when we start using yarn pnp because each version will have only one path to resolve.

**Comment by TrySound** [comment]
The current solution is the best one. There's nothing to fix.
