### ISSUE TITLE
Position of dragged element wrong in Chrome

### ISSUE THREAD

**Issue by hohenp** [atlassian/react-beautiful-dnd#882]
When a dragg an element, the Position is wrong in Chrome. In IE ist works correct.
The Position seems to be relative to top:0, left:0.
As far as I move away from 0,0 the Position keeps worse.

I have attached a Video with the behavior.
Chrome 70, react-beautiful-dnd: 9.0.2
[issueDNDChrome.zip](https://github.com/atlassian/react-beautiful-dnd/files/2538289/issueDNDChrome.zip)

**Comment by cozuya** [comment]
I'm having the same issue so strange timing as I just picked up this library.  Doesn't work in any browser though.  I'm pretty sure its due to the `transform` issues called on in the docs: https://github.com/atlassian/react-beautiful-dnd#warning-position-fixed . I'm looking into the portal fallback now.  I'm using Material UI on a `Popover` element using `react-swipeable-views` and there is some `transform`s in the parent components.
