### ISSUE TITLE
Drag&Drop works incorrectly for scrollable container

### ISSUE THREAD

**Issue by bobrovnik** [atlassian/react-beautiful-dnd#89]
## Bug
Demo: http://g.recordit.co/Ep9vM3PPeq.gif

Drag&Drop for cards from the last column does not work correctly. Seems scroll is not taken into account 

### Expected behavior
Drag&Drop should work in same way with or without scroll

### Actual behavior
Drag&Drop for cards which exceed initially scrollable screen is working incorrectly. Gif shows this behavior http://g.recordit.co/Ep9vM3PPeq.gif
![ep9vm3ppeq](https://user-images.githubusercontent.com/208444/30461648-33974050-9a03-11e7-80ee-74bd884f06e9.gif)

### Steps to reproduce
1) Open https://react-beautiful-dnd.netlify.com/?selectedKind=board&selectedStory=task%20board&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel
2) Resize screen to move the last board column outside of screen
3) Pick up card from the last column
4) Card would be ranking inside incorrect column

### Browser version
- Chrome for Mac Version 60.0.3112.113 (Official Build) (64-bit)
- Latest Firefox for Mac

### Demo
http://g.recordit.co/Ep9vM3PPeq.gif

**Comment by alexreardon** [comment]
Great issue submission - thank you. I'll look into it now

**Comment by alexreardon** [comment]
The issue is caused by having a shared scroll container between the `Droppables` - something we have not intended to support yet. We needed a scroll container in this case to ensure that the background colour goes over the scroll. Rather than using a scroll container now we leverage `display: inline-flex` on the root level. I think we should support the usecase of a shared wrapping scroll container - but the immediate issue is resolved. We currently do not support nested or shared parent scroll parents. I think we should support a single shared scroll parent going forward.

**Comment by davidpene** [comment]
Hi @alexreardon do you have a timeline of when this issue may be fixed? 
Or do you have an immediate (quick) resolution, I can use to solve this?

Cheers

**Comment by alexreardon** [comment]
It is already fixed! #111. It should be released very soon
