### ISSUE TITLE
Programatic cancelling of a drag

### ISSUE THREAD

**Issue by alexreardon** [atlassian/react-beautiful-dnd#9]
Once a drag has started there is no way to cancel it except through user input. There may be a scenario where the application wants to clear any current drag

**Comment by alexreardon** [comment]
For now you can do this by triggering an 'escape' keydown event on the window

```js
const dispatchWindowKeyDownEvent = (
  keyCode: number,
): KeyboardEvent => {
  const event = new window.KeyboardEvent('keydown', {
    bubbles: true,
    cancelable: true,
    keyCode,
  });
  window.dispatchEvent(event);
  return event;
};

const escape: number = 27;
const windowEscape = dispatchWindowKeyDownEvent.bind(null, escape);

// boom
escape();
```

**Comment by mheavenor** [comment]
Hey @alexreardon,

I am having trouble using the above code snippet. In typescript, the interface for `KeyboardEventInit` (the type of the second argument in `KeyboardEvent`) does not contain the `keyCode` property. Even after creating the event I cant explicitly set the `keyCode` property as it is read only. 

As per the MDN docs, `keyCode` is deprecated. Maybe the code should be changed so that the `code` property is checked on the event rather than `keyCode`.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

**Comment by alexreardon** [comment]
The code I listed is just a work around. You can trigger an escape key press however you like. While `event.keyCode` is deprecated it still works everywhere. Newer methods such as [`event.key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) do not have as wide support

**Comment by alexreardon** [comment]
This might be possible as a part of work relating to #1225

**Comment by alexreardon** [comment]
This will ship in #1317 as a part of #162
