### ISSUE TITLE
Source Droppable not re renders after drop

### ISSUE THREAD

**Issue by Serezon** [atlassian/react-beautiful-dnd#942]
## Bug or feature request?
Bug
### Project
Simple board with lists and items (React&Redux)
### Expected behavior
Item moves from one list to another.
### Actual behavior
After move there's copy of this item at it previous position. If I'll try to drag this item(doesn't matter source or destination list) item in source disappear until I free it. If I update source list - it disappear and everything becomes okay. Seems like source list gets rerendered only on drag start.
### Thoughts
Should I delete item in source list on drag start?(unneeded state changes)
### What version of `React` are you using?
16.6.0
### What version of `react-beautiful-dnd` are you running?
10.0.1
### How it looks like
[GIF](https://s2.gifyu.com/images/weirdOne.gif)

**Comment by Serezon** [comment]
Thank you for your answer! I already saw your course, it's awesome, but I can't spot the mistake. 
Here's sandbox: [Click here](https://codesandbox.io/s/kkw4r2yjkv)

**Comment by alexreardon** [comment]
Here you go: https://codesandbox.io/s/9o19r76n9r

It looks like you are modifying an existing board rather than creating a new one. Because the reference is not changing, redux is blocking the render update	

You can opt out of this check by setting `pure: false` in your `connect` function

```js
export default connect(
  mapStateToProps,
  // mapDispatchToProps,
  null,
  // mergeProps
  null,
  { pure: false }
)(Board);
```

Alternatively you should update the reference of `board` when you are updating it rather than modifying the existing one
