### ISSUE TITLE
Can't move item with keyboard

### ISSUE THREAD

**Issue by FrontendMetis** [atlassian/react-beautiful-dnd#990]
## Bug or feature request?

(Bug)

## Description
So, when I have difrence height on title can't move item with keyboard

### Demo
https://youtu.be/878KLB-KiNI

**Comment by alexreardon** [comment]
See here: https://medium.com/@alexandereardon/friction-gravity-and-collisions-3adac3a94e19

Currently we exclude droppables that are outside of the size of the current droppable. Otherwise the user might end up moving to a list they did not expect and could be quite jarring in some extreme cases

Let me know what you think

![](https://cdn-images-1.medium.com/max/2000/1*emXmlpukM6RW1rQUjA9HWQ.png)
